In [4]:
import numpy as np

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.save('df1', arr)

In [11]:
arr2 = np.load('df1.npy')
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr1 = np.arange(20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
np.savez('arrays', a = arr, b = arr1)

In [23]:
arrays = np.load('arrays.npz')
arrays

NpzFile 'arrays.npz' with keys: a, b

In [26]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
np.savez_compressed('arr_comp', a = arr, b = arr1)

# Chiziqli algebra
NumPy va Chiziqli Algebra haqida yaxshi maqola: https://towardsdatascience.com/introduction-to-linear-algebra-with-numpy-79adeb7bc060

In [29]:
arr*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [40]:
x = np.array([[1.,2.,3], [4,5,6]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [41]:
y = np.array([[-2,6], [4,3],[56,-4]])
y

array([[-2,  6],
       [ 4,  3],
       [56, -4]])

In [45]:
x.dot(y)

array([[174.,   0.],
       [348.,  15.]])

In [46]:
np.dot(x,y)

array([[174.,   0.],
       [348.,  15.]])

In [50]:
y.dot(x)

array([[ 22.,  26.,  30.],
       [ 16.,  23.,  30.],
       [ 40.,  92., 144.]])

In [51]:
ar_c = np.array([0, 1, 2, 3])

In [52]:
ar_c.cumsum()

array([0, 1, 3, 6])

In [55]:
ar_c.dtype

dtype('int32')

In [57]:
# masala

In [58]:
a = np.array([1,2,3,5,8])
b = np.array([0, 3,4,2,1])

In [60]:
c = a+b
c

array([1, 5, 7, 7, 9])

In [61]:
c = c*a
c

array([ 1, 10, 21, 35, 72])

In [62]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [64]:
print(a.itemsize)

4


In [65]:
ary = np.array([1,2,3,5,8])
ary = ary +1

In [66]:
ary[1]

3

In [68]:
a = ary = np.array([1,2,3,5,8])

In [70]:
a.ndim

1

In [71]:
a = np.array([1,2,3,4,5])
b = np.arange(0,10,2)

In [72]:
c = a+b

In [73]:
c[4]

13

In [80]:
# NumPy versiyasini chop etish
print(np.__version__)

# NumPy konfiguratsiyasini chop etish
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/User/anaconda3/Library/include
    lib directory: C:/Users/User/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
    

In [76]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/User/anaconda3/Library/include
    lib directory: C:/Users/User/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
    cpu: x8