In [2]:
import numpy as np

In [3]:
my_list = list(range(100_000))
my_array = np.array(range(100_000))

In [24]:
%time for _ in range(10): [x*2 for x in my_list]  # Normal

Wall time: 103 ms


In [25]:
%time for _ in range(10): my_array*2

Wall time: 1.99 ms


# Greating Array

In [27]:
listlar = [5,6,4.5,8]
arr1 = np.array(listlar)
arr1

array([5. , 6. , 4.5, 8. ])

In [30]:
arr1.ndim

1

In [41]:
data4 = [[1,5,7,5], [1,2,2,9]]
arr2 = np.array(data4)

In [42]:
arr2.ndim

2

In [43]:
arr2

array([[1, 5, 7, 5],
       [1, 2, 2, 9]])

In [44]:
print (f"Massiv o'lcchami {arr2.shape} va elementlar soni {arr2.size} ta")

Massiv o'lcchami (2, 4) va elementlar soni 8 ta


In [50]:
arr4 = np.zeros(shape = (5,5))

arr4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [53]:
arr5 = np.ones((5,5))

arr5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
arr6 = np.arange(2,50,5)
arr6

array([ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47])

In [58]:
def one_dim(n):
    """ n ta elementdan tashkil topgan 1-o'lchamli massiv """
    if n > 0 and isinstance(n, int):  # n musbat butun sonligini tekshirish
        return np.random.rand(n)  # Tasodifiy sonlardan iborat massiv
    else:
        raise ValueError("n musbat butun son bo'lishi kerak")

In [59]:
def two_dim(r, c):
    """r ta qator, c ta ustundan tashkil topgan 2-o'lchamli massiv"""
    if r > 0 and c > 0 and isinstance(r, int) and isinstance(c, int):  # r va c musbat butun sonligini tekshirish
        return np.random.rand(r, c)  # Tasodifiy sonlardan iborat 2-o'lchamli massiv
    else:
        raise ValueError("r va c musbat butun sonlar bo'lishi kerak")


In [61]:
massiv = two_dim(5, 5)  # 3 қатор ва 4 устунли массив яратиш
print(massiv)


[[0.3037038  0.33274112 0.98543247 0.12163021 0.0309442 ]
 [0.29651887 0.2082797  0.40706557 0.23065697 0.3786746 ]
 [0.24648311 0.18379004 0.62303911 0.15535051 0.98897956]
 [0.08760721 0.22286532 0.95844238 0.9378052  0.62963519]
 [0.50577901 0.32215604 0.1268491  0.05825904 0.8766101 ]]


In [2]:
a= 55
print (f"lkjasdlkfj {a}")

lkjasdlkfj 55
