<a href="https://colab.research.google.com/github/ulubeykhuja/mohir_dev_lessons/blob/main/MLga_tayyorlash_uzim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import sklearn

In [22]:
URL = "https://raw.githubusercontent.com/ageron/handson-ml2/refs/heads/master/datasets/housing/housing.csv"
df = pd.read_csv(URL)
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [23]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(df, test_size=0.2, random_state=42)

In [24]:
housing = train_set.drop('median_house_value', axis=1) # bashorat qilinadigan ustunni tashlash
housing_labels = train_set['median_house_value'].copy() # uni alohida saqlash

## Bo'sh qiymatlarni tashlash

In [5]:
# 1-usul: Bo'sh qiymatlarni tashlash
housing.dropna(subset=['total_bedrooms'])

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
14196    -117.03     32.71                33.0       3126.0           627.0   
8267     -118.16     33.77                49.0       3382.0           787.0   
17445    -120.48     34.66                 4.0       1897.0           331.0   
14265    -117.11     32.69                36.0       1421.0           367.0   
2271     -119.80     36.78                43.0       2382.0           431.0   
...          ...       ...                 ...          ...             ...   
11284    -117.96     33.78                35.0       1330.0           201.0   
11964    -117.43     34.02                33.0       3084.0           570.0   
5390     -118.38     34.03                36.0       2101.0           569.0   
860      -121.96     37.58                15.0       3575.0           597.0   
15795    -122.42     37.77                52.0       4226.0          1315.0   

       population  households  median_income ocean_proximity  
14196      2300.0       623.0         3.2596      NEAR OCEAN  
8267       1314.0       756.0         3.8125      NEAR OCEAN  
17445       915.0       336.0         4.1563      NEAR OCEAN  
14265      1418.0       355.0         1.9425      NEAR OCEAN  
2271        874.0       380.0         3.5542          INLAND  
...           ...         ...            ...             ...  
11284       658.0       217.0         6.3700       <1H OCEAN  
11964      1753.0       449.0         3.0500          INLAND  
5390       1756.0       527.0         2.9344       <1H OCEAN  
860        1777.0       559.0         5.7192       <1H OCEAN  
15795      2619.0      1242.0         2.5755        NEAR BAY  

[16512 rows x 9 columns]

In [6]:
# 2-usul: Ustunni tashlash
housing.drop('total_bedrooms', axis=1)

longitude  latitude  housing_median_age  total_rooms  population  \
14196    -117.03     32.71                33.0       3126.0      2300.0   
8267     -118.16     33.77                49.0       3382.0      1314.0   
17445    -120.48     34.66                 4.0       1897.0       915.0   
14265    -117.11     32.69                36.0       1421.0      1418.0   
2271     -119.80     36.78                43.0       2382.0       874.0   
...          ...       ...                 ...          ...         ...   
11284    -117.96     33.78                35.0       1330.0       658.0   
11964    -117.43     34.02                33.0       3084.0      1753.0   
5390     -118.38     34.03                36.0       2101.0      1756.0   
860      -121.96     37.58                15.0       3575.0      1777.0   
15795    -122.42     37.77                52.0       4226.0      2619.0   

       households  median_income ocean_proximity  
14196       623.0         3.2596      NEAR OCEAN  
8267        756.0         3.8125      NEAR OCEAN  
17445       336.0         4.1563      NEAR OCEAN  
14265       355.0         1.9425      NEAR OCEAN  
2271        380.0         3.5542          INLAND  
...           ...            ...             ...  
11284       217.0         6.3700       <1H OCEAN  
11964       449.0         3.0500          INLAND  
5390        527.0         2.9344       <1H OCEAN  
860         559.0         5.7192       <1H OCEAN  
15795      1242.0         2.5755        NEAR BAY  

[16512 rows x 8 columns]

In [7]:
# 3-usul: NaN qiymtlarni almashtirish
median = housing['total_bedrooms'].median()
#median
housing['total_bedrooms'].fillna(median)

14196     627.0
8267      787.0
17445     331.0
14265     367.0
2271      431.0
          ...  
11284     201.0
11964     570.0
5390      569.0
860       597.0
15795    1315.0
Name: total_bedrooms, Length: 16512, dtype: float64

## **3-qadam. MLga tayyorgarlik. NaN qiymatlarni almashtirish**

In [12]:
# datadagi hamma Nan qiymatlarni medianga to'ldiradi
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='median')
imputer.fit(housing)
# !!!sonsiz qiymatlar bo'lgani uchun xato beradi

ValueError: Cannot use median strategy with non-numeric data:
could not convert string to float: 'NEAR OCEAN'

In [13]:
housing_num = housing.drop("ocean_proximity", axis = 1)
housing_num

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
14196    -117.03     32.71                33.0       3126.0           627.0   
8267     -118.16     33.77                49.0       3382.0           787.0   
17445    -120.48     34.66                 4.0       1897.0           331.0   
14265    -117.11     32.69                36.0       1421.0           367.0   
2271     -119.80     36.78                43.0       2382.0           431.0   
...          ...       ...                 ...          ...             ...   
11284    -117.96     33.78                35.0       1330.0           201.0   
11964    -117.43     34.02                33.0       3084.0           570.0   
5390     -118.38     34.03                36.0       2101.0           569.0   
860      -121.96     37.58                15.0       3575.0           597.0   
15795    -122.42     37.77                52.0       4226.0          1315.0   

       population  households  median_income  
14196      2300.0       623.0         3.2596  
8267       1314.0       756.0         3.8125  
17445       915.0       336.0         4.1563  
14265      1418.0       355.0         1.9425  
2271        874.0       380.0         3.5542  
...           ...         ...            ...  
11284       658.0       217.0         6.3700  
11964      1753.0       449.0         3.0500  
5390       1756.0       527.0         2.9344  
860        1777.0       559.0         5.7192  
15795      2619.0      1242.0         2.5755  

[16512 rows x 8 columns]

In [25]:
housing.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
ocean_proximity       0
dtype: int64

In [27]:
imputer.fit(housing_num)

SimpleImputer(strategy='median')

In [29]:
# har bir ustun uchun median hisobladi
imputer.statistics_

array([-118.51  ,   34.26  ,   29.    , 2129.    ,  437.    , 1167.    ,
        410.    ,    3.5458])

In [32]:
X = imputer.transform(housing_num)
X

array([[-1.1703e+02,  3.2710e+01,  3.3000e+01, ...,  2.3000e+03,
         6.2300e+02,  3.2596e+00],
       [-1.1816e+02,  3.3770e+01,  4.9000e+01, ...,  1.3140e+03,
         7.5600e+02,  3.8125e+00],
       [-1.2048e+02,  3.4660e+01,  4.0000e+00, ...,  9.1500e+02,
         3.3600e+02,  4.1563e+00],
       ...,
       [-1.1838e+02,  3.4030e+01,  3.6000e+01, ...,  1.7560e+03,
         5.2700e+02,  2.9344e+00],
       [-1.2196e+02,  3.7580e+01,  1.5000e+01, ...,  1.7770e+03,
         5.5900e+02,  5.7192e+00],
       [-1.2242e+02,  3.7770e+01,  5.2000e+01, ...,  2.6190e+03,
         1.2420e+03,  2.5755e+00]])

In [35]:
# aslida 2 lasini birdan chaqirsa bo'ladi
X = imputer.fit_transform(housing_num)

In [38]:
# X ni df ga aylantirish
housing_tr = pd.DataFrame(X, columns=housing_num.columns, index=housing_num.index)
housing_tr.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
14196    -117.03     32.71                33.0       3126.0           627.0   
8267     -118.16     33.77                49.0       3382.0           787.0   
17445    -120.48     34.66                 4.0       1897.0           331.0   
14265    -117.11     32.69                36.0       1421.0           367.0   
2271     -119.80     36.78                43.0       2382.0           431.0   

       population  households  median_income  
14196      2300.0       623.0         3.2596  
8267       1314.0       756.0         3.8125  
17445       915.0       336.0         4.1563  
14265      1418.0       355.0         1.9425  
2271        874.0       380.0         3.5542

# ***3-qadam. MLga tayyorgarlik. Matnlar. SimpleEncoder***

In [40]:
# categirical ma'lumotlar
housing_cat = housing[['ocean_proximity']]
housing_cat.head()

ocean_proximity
14196      NEAR OCEAN
8267       NEAR OCEAN
17445      NEAR OCEAN
14265      NEAR OCEAN
2271           INLAND

In [49]:
housing_cat.value_counts()
#.sort_values(ascending = False)

ocean_proximity
<1H OCEAN          7341
INLAND             5227
NEAR OCEAN         2086
NEAR BAY           1854
ISLAND                4
Name: count, dtype: int64

In [54]:
# categorical ni songa otkazish
# sklearn dan foydalanib

from sklearn.preprocessing import OrdinalEncoder

# yangi obyekt
ordinal_encoder = OrdinalEncoder()

housing_cat_encoded = ordinal_encoder.fit_transform(housing_cat)
housing_cat_encoded[:10]

array([[4.],
       [4.],
       [4.],
       [4.],
       [1.],
       [0.],
       [0.],
       [3.],
       [0.],
       [0.]])

# *3-qadam. MLga tayyorgarlik. Matnlar. OneHotEncoder*

In [53]:
from sklearn.preprocessing import OneHotEncoder

cat_encoder = OneHotEncoder()
housing_cat_1hot = cat_encoder.fit_transform(housing_cat)
housing_cat_1hot.toarray()

# kamchiligi - kategoriya lo'p bo'lsa ustun ko'payadi, sekilatadi

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [56]:
housing_onehot = pd.get_dummies(housing['ocean_proximity'])
housing_onehot

<1H OCEAN  INLAND  ISLAND  NEAR BAY  NEAR OCEAN
14196      False   False   False     False        True
8267       False   False   False     False        True
17445      False   False   False     False        True
14265      False   False   False     False        True
2271       False    True   False     False       False
...          ...     ...     ...       ...         ...
11284       True   False   False     False       False
11964      False    True   False     False       False
5390        True   False   False     False       False
860         True   False   False     False       False
15795      False   False   False      True       False

[16512 rows x 5 columns]