<a href="https://colab.research.google.com/github/ulubeykhuja/mohir_dev_lessons/blob/main/U_Khujakulov_javoblar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

**Ulug'bek Xo'jaqulov **

In [6]:
# 1. NumPy kutubxonasini np nomi ostida yuklang va numpy kutubxonasini chop eting.
import numpy as np
print("NumPy kutubxonasi:", np)
print("NumPy versiyasi:", np.__version__)
# NumPy konfiguratsiyasini ko'rsatish
np.show_config()

NumPy kutubxonasi: <module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>
NumPy versiyasi: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,

In [7]:
# 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

import numpy as np

my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4, 5])

In [50]:
# 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.
zero_arr= np.zeros(9)
zero_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
#  4. Massiv yarating va uning xotira hajmini toping.
arr_1 = np.arange(1, 55, 5)
print (f"Massiv {arr_1}")
print (f"Elementlar soni {np.size(arr_1)} ta")
print (f"1 ta element hajmi {arr_1.itemsize} bayt")

Massiv [ 1  6 11 16 21 26 31 36 41 46 51]
Elementlar soni 11 ta
1 ta element hajmi 8 bayt


In [48]:
#  5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [49]:
# 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin,
# lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.

vector = np.zeros(12)
vector[5] = 1
vector

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [56]:
#  7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.
vector_1 = np.arange(20, 59, 1)
vector_1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58])

In [55]:
# 8. Vektor yarating va uni teskari o'zgartiring
vector_2 = np.arange(10)
reversed_vector = vector_2[::-1]
print("Vektor:", vector_2)
print("Teskari vektor:", reversed_vector)

Vektor: [0 1 2 3 4 5 6 7 8 9]
Teskari vektor: [9 8 7 6 5 4 3 2 1 0]


In [64]:
# 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.
matx = np.arange(12, 21).reshape(3,3)
print  ("3x3 matrisa: \n",  matx)

3x3 matrisa: 
 [[12 13 14]
 [15 16 17]
 [18 19 20]]


In [66]:
# 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping. [3, 7, 0, 0, 9, 0]
arr_2 = np.array([3, 7, 0, 0, 9, 0])
non_zero = np.nonzero(arr_2)
non_zero

(array([0, 1, 4]),)

In [75]:
# 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.
arr_3 = np.random.rand(2,2,2)
arr_3

array([[[0.31580909, 0.19509017],
        [0.75105639, 0.55062824]],

       [[0.86078098, 0.05914512],
        [0.58315852, 0.98266765]]])

In [81]:
# 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping
arr_4 = np.random.rand(9,9)
arr_4

print ("Massiv maksimumi: ", arr_4.max())
print ("Massiv minimumi: ",  arr_4.min())

Massiv maksimumi:  0.9990462674288261
Massiv minimumi:  0.005765255443722084


In [82]:
# 13. Quyidagi misol qanday natija beradi?
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1

False

In [83]:
# 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning ko'paytmasini hisoblang.
matrix_1 = np.random.rand(6, 3)
matrix_2 = np.random.rand(3, 4)

product_matrix = np.dot(matrix_1, matrix_2)

print("Birinchi matritsa:\n", matrix_1)
print("Ikkinchi matritsa:\n", matrix_2)
print("Ko'paytma matritsasi:\n", product_matrix)

Birinchi matritsa:
 [[0.38282828 0.99721654 0.42153574]
 [0.81873924 0.10063854 0.97185117]
 [0.376534   0.58580667 0.06707176]
 [0.94617914 0.44122546 0.38742052]
 [0.43020723 0.1695526  0.19769386]
 [0.94899763 0.24268307 0.03335773]]
Ikkinchi matritsa:
 [[0.15381014 0.51734793 0.93716501 0.53573627]
 [0.3696135  0.67946528 0.10721979 0.99637684]
 [0.90794877 0.80182599 0.35448945 0.91906968]]
Ko'paytma matritsasi:
 [[0.81020043 1.21362774 0.61512459 1.58611918]
 [1.04551884 1.27120897 1.1225952  1.43210115]
 [0.33533452 0.64661426 0.43946079 0.84705074]
 [0.66037282 1.09994505 1.07137057 1.30259577]
 [0.30833506 0.496288   0.49143494 0.58111033]
 [0.26595151 0.68260378 0.92721276 0.78087432]]


In [84]:
# 15. Quyidagi misol qanday natija beradi?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [85]:
# 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.
array_a = np.array([1, 2])
array_b = np.array([4, 5])

print("a > b:", array_a > array_b)
print("a >= b:", array_a >= array_b)
print("a < b:", array_a < array_b)
print("a <= b:", array_a <= array_b)


a > b: [False False]
a >= b: [False False]
a < b: [ True  True]
a <= b: [ True  True]


In [86]:
# 17. Quyidagi misol qanday natija beradi?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-86-8095f4dba212>:2: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-86-8095f4dba212>:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-86-8095f4dba212>:4: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

In [87]:
# 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 5, 6, 7, 8])

common_values = np.intersect1d(array1, array2)

print("Birinchi massiv:", array1)
print("Ikkinchi massiv:", array2)
print("Umumiy qiymatlar:", common_values)

Birinchi massiv: [1 2 3 4 5]
Ikkinchi massiv: [3 5 6 7 8]
Umumiy qiymatlar: [3 5]


In [88]:
# 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.
random_array = np.random.uniform(-10, 10, 10)  # -10 dan 10 gacha 10 ta tasodifiy son

print("Dastlabki massiv:", random_array)

# 1. Modulus operatori (%)
integer_part_modulus = random_array % 1
print("Modulus operatori:", integer_part_modulus)

# 2. np.floor()
integer_part_floor = np.floor(random_array)
print("np.floor():", integer_part_floor)

# 3. astype()
integer_part_astype = random_array.astype(int)
print("astype(int):", integer_part_astype)

# 4. np.trunc()
integer_part_trunc = np.trunc(random_array)
print("np.trunc():", integer_part_trunc)

Dastlabki massiv: [ 5.44969229 -2.32831133 -0.50998651  0.0828306   7.77311526 -9.6402535
  6.85704563  6.75885097 -5.18250964  2.19762394]
Modulus operatori: [0.44969229 0.67168867 0.49001349 0.0828306  0.77311526 0.3597465
 0.85704563 0.75885097 0.81749036 0.19762394]
np.floor(): [  5.  -3.  -1.   0.   7. -10.   6.   6.  -6.   2.]
astype(int): [ 5 -2  0  0  7 -9  6  6 -5  2]
np.trunc(): [ 5. -2. -0.  0.  7. -9.  6.  6. -5.  2.]


In [90]:
# 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.

matrix = np.zeros((3, 3))
for i in range(3):
    matrix[i] = i
matrix

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.]])

In [91]:
# 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing
random_vector = np.random.rand(10)
sorted_vector = np.sort(random_vector)

print("Tasodifiy vektor:", random_vector)
print("O'sish tartibida saralangan vektor:", sorted_vector)

Tasodifiy vektor: [0.83805714 0.82900113 0.00372942 0.54515951 0.864565   0.09537963
 0.29510736 0.33208642 0.96433165 0.17079089]
O'sish tartibida saralangan vektor: [0.00372942 0.09537963 0.17079089 0.29510736 0.33208642 0.54515951
 0.82900113 0.83805714 0.864565   0.96433165]


In [92]:
# 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring
A = np.random.rand(5)  # 5 ta tasodifiy elementdan iborat massiv
B = np.random.rand(5)

print("A massivi:", A)
print("B massivi:", B)

# Massivlarning tengligini np.allclose() bilan tekshirish
are_close = np.allclose(A, B)
print(f"Massivlar np.allclose() bo'yicha tengmi? {are_close}")

# Massivlarning tengligini np.array_equal() bilan tekshirish
are_equal = np.array_equal(A, B)
print(f"Massivlar np.array_equal() bo'yicha tengmi? {are_equal}")

A massivi: [0.44997838 0.51882851 0.91208686 0.24045984 0.21624419]
B massivi: [0.7199508  0.87670895 0.01746441 0.25590721 0.53090391]
Massivlar np.allclose() bo'yicha tengmi? False
Massivlar np.array_equal() bo'yicha tengmi? False


In [93]:
# 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.
matrix_1 = np.random.rand(6, 3)
matrix_2 = np.random.rand(3, 4)

mult = np.dot(matrix_1, matrix_2)

print("Birinchi matritsa:\n", matrix_1)
print("Ikkinchi matritsa:\n", matrix_2)
print("Ko'paytma matritsasi:\n", mult)

Birinchi matritsa:
 [[0.47712393 0.64413381 0.00337205]
 [0.17765292 0.81761764 0.19464032]
 [0.61262131 0.23511844 0.74668099]
 [0.16679778 0.88533054 0.11190254]
 [0.02327384 0.96734277 0.48671791]
 [0.07410909 0.89683942 0.83282046]]
Ikkinchi matritsa:
 [[0.2195247  0.71417163 0.46337551 0.7441289 ]
 [0.83289588 0.19494782 0.07890953 0.52265066]
 [0.23993522 0.52223296 0.56244835 0.98827143]]
Ko'paytma matritsasi:
 [[0.64204596 0.46808186 0.27381245 0.69503118]
 [0.76669063 0.38791505 0.25631296 0.75188255]
 [0.50946975 0.87329401 0.72239629 1.31667752]
 [0.80085375 0.3501547  0.21009042 0.69742772]
 [0.92758575 0.45938302 0.36087077 1.00391048]
 [0.96306559 0.66268979 0.57352801 1.3469331 ]]


In [95]:
# 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring
vector = np.random.rand(5)
print("Original vector:", vector)

max_index = np.argmax(vector)
vector[max_index] = 0

print("O'zgargan vector:", vector)

Original vector: [0.89035718 0.08370194 0.56356778 0.77287425 0.93622918]
O'zgargan vector: [0.89035718 0.08370194 0.56356778 0.77287425 0.        ]


In [98]:
# 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.
bugun = np.datetime64('today')
kecha = bugun - np.timedelta64(1, 'D')
ertaga = bugun + np.timedelta64(1, 'D')

print("Kecha:", kecha)
print("Bugun:", bugun)
print("Ertaga:", ertaga)

Kecha: 2024-12-27
Bugun: 2024-12-28
Ertaga: 2024-12-29


In [99]:
# 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.

start_date = np.datetime64('2016-01-01')
end_date = np.datetime64('2016-02-01')

dates = np.arange(start_date, end_date, dtype='datetime64[D]')

dates

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

In [100]:
# 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.
# 1. Modulus operatori (%)
integer_part_modulus = random_array % 1
print("Modulus operatori:", integer_part_modulus)

# 2. np.floor()
integer_part_floor = np.floor(random_array)
print("np.floor():", integer_part_floor)

# 3. astype()
integer_part_astype = random_array.astype(int)
print("astype(int):", integer_part_astype)

# 4. np.trunc()
integer_part_trunc = np.trunc(random_array)
print("np.trunc():", integer_part_trunc)

Modulus operatori: [0.44969229 0.67168867 0.49001349 0.0828306  0.77311526 0.3597465
 0.85704563 0.75885097 0.81749036 0.19762394]
np.floor(): [  5.  -3.  -1.   0.   7. -10.   6.   6.  -6.   2.]
astype(int): [ 5 -2  0  0  7 -9  6  6 -5  2]
np.trunc(): [ 5. -2. -0.  0.  7. -9.  6.  6. -5.  2.]


In [101]:
# 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.
a = np.random.rand(5)
b = np.random.rand(5)
c = np.random.rand(5)

# np.add.reduce bilan yig'indini
sum_fast = np.add.reduce([a, b, c])

# np.sum bilan yig'indini
sum_slow = np.sum([a,b,c])


print("np.add.reduce yordamida yig'indi:", sum_fast)
print("np.sum yordamida yig'indi:", sum_slow)

np.add.reduce yordamida yig'indi: [0.70538755 1.2420024  1.19686497 2.17343535 2.26539146]
np.sum yordamida yig'indi: 7.58308172325598


In [102]:
# 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing
vector = np.array([1, 2, 3, 4, 5])
zeros = np.zeros(len(vector) * 4 - 3, dtype=int)
zeros[::4] = vector
zeros

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

In [104]:
# 30. Quyidagi a massiv berilgan,
# a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi
# b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?
from numpy.lib.stride_tricks import as_strided

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
b = as_strided(a, shape=(11, 4), strides=(a.itemsize, a.itemsize))
b

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

In [106]:
# 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.
arr = np.array([1, 2, 2, 3, 4, 4, 4, 5, 1, 2])

# O'xshash qiymatlarni topish
unique_elements, counts = np.unique(arr, return_counts=True)

print("Massiv:", arr)
print("unique elementlar:", unique_elements)
print("Har bir elementning soni:", counts)

# O'xshash qiymatlarni topishning boshqa usuli (faqat o'xshash qiymatlarni chiqaradi)
duplicates = unique_elements[counts > 1]
print("O'xshash elementlar:", duplicates)

Massiv: [1 2 2 3 4 4 4 5 1 2]
unique elementlar: [1 2 3 4 5]
Har bir elementning soni: [2 3 1 3 1]
O'xshash elementlar: [1 2 4]


In [107]:
# 32.  O'lchamlari 4x4 matritsa yarating, so'ng uning diagonal elementlarini 1 ga o'zgartiring.

matrix = np.zeros((4, 4))
np.fill_diagonal(matrix, 1)
matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])